[tool.poetry]
name = "spinning-cube"
version = "0.1.0"
description = ""
authors = ["Jason Han <hanjasn@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
